/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class loongplugin_word2vec_word2vecUtil */

#ifndef _Included_loongplugin_word2vec_word2vecUtil
#define _Included_loongplugin_word2vec_word2vecUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loongplugin_word2vec_word2vecUtil
 * Method:    word2vec
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_loongplugin_word2vec_word2vecUtil_word2vec
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     loongplugin_word2vec_word2vecUtil
 * Method:    distance
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_loongplugin_word2vec_word2vecUtil_distance
  (JNIEnv *, jclass, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
